-- Selección de índices para el acceso a la información a través de la DB

-- Tabla de estratos

CREATE INDEX STRATUMS_ID_IDX ON APP_DATOS_IMPRESION.STRATUMS (ID);

-- Tabla de clientes

CREATE INDEX CLIENTS_ID_IDX ON APP_DATOS_IMPRESION.CLIENTS (ID);

-- Tabla de periodos

CREATE INDEX PERIOD_MONTH_YEAR_IDX ON APP_DATOS_IMPRESION.PERIODS (MONTH_YEAR);

-- Tabla de consumos

CREATE INDEX CONSUMPTIONS_ID_IDX ON APP_DATOS_IMPRESION.CONSUMPTIONS (ID);

-- Tabla de facturas

CREATE INDEX BILLS_ID_IDX ON APP_DATOS_IMPRESION.BILLS (ID);