-- Index para estratos

CREATE INDEX STRATUMS_ID_IDX ON APP_DATOS_IMPRESION.STRATUMS (ID);

-- Index para clientes

CREATE INDEX CLIENTS_ID_IDX ON APP_DATOS_IMPRESION.CLIENTS (ID);

-- Index para periodos

CREATE INDEX PERIOD_MONTH_YEAR_IDX ON APP_DATOS_IMPRESION.PERIODS (MONTH_YEAR);

-- Index para consumos

CREATE INDEX CONSUMPTIONS_ID_IDX ON APP_DATOS_IMPRESION.CONSUMPTIONS (ID);

-- Index para facturas

CREATE INDEX BILLS_ID_IDX ON APP_DATOS_IMPRESION.BILLS (ID);