-- Agregando algunos periodos hasta la actualidad

INSERT /*+ append */ ALL
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (1, '01/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (2, '02/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (3, '03/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (4, '04/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (5, '05/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (6, '06/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (7, '07/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (8, '08/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (9, '09/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (10, '10/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (11, '11/2022')
     into APP_DATOS_IMPRESION.PERIODS (ID, MONTH_YEAR) values (12, '12/2022')
SELECT * FROM dual;
PROMPT Periodos agregados