-- Agregando estratos estándar a la tabla

INSERT /*+ append */ ALL
	INTO APP_DATOS_IMPRESION.STRATUMS (ID,COST_PER_CM,BUSINESS_DAYS) VALUES (1,1568.0,60)
	INTO APP_DATOS_IMPRESION.STRATUMS (ID,COST_PER_CM,BUSINESS_DAYS) VALUES (2,2351.99,50)
	INTO APP_DATOS_IMPRESION.STRATUMS (ID,COST_PER_CM,BUSINESS_DAYS) VALUES (3,3429.99,40)
	INTO APP_DATOS_IMPRESION.STRATUMS (ID,COST_PER_CM,BUSINESS_DAYS) VALUES (4,3919.99,30)
	INTO APP_DATOS_IMPRESION.STRATUMS (ID,COST_PER_CM,BUSINESS_DAYS) VALUES (5,5879.99,20)
	INTO APP_DATOS_IMPRESION.STRATUMS (ID,COST_PER_CM,BUSINESS_DAYS) VALUES (6,6271.98,15)
SELECT * FROM dual;
PROMPT Estratos agregados